### ISSUE TITLE
autoload.php error

### ISSUE THREAD

**Issue by aneeshasokan13** [mkalkbrenner/HVClientLibPHP#5]
Hi,
I downloaded HVRawConnectorPHP library for access data from Microsoft HealthVault. I added this library source code in htdocs and run demo_app/index.php in browser. But it shows error like this

Warning: require(../vendor/autoload.php) [function.require]: failed to open stream: No such file or directory in C:\xampp\htdocs\HVClientLibPHP-master\demo_app\index.php on line 13

Fatal error: require() [function.require]: Failed opening required '../vendor/autoload.php' (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\HVClientLibPHP-master\demo_app\index.php on line 13

How it can solve? By using default library files, can i access any data/xml from health vault?

Thanks.

**Comment by mkalkbrenner** [comment]
You should not download it but use composer to install it. Composer will create the autoloader.
But instead of HVRawConnectorPHP you you should use HVClientLibPHP. Follow the instructions here:
http://mkalkbrenner.github.io/HVClientLibPHP/

**Comment by aneeshasokan13** [comment]
I downloaded HVClientLibPHP. It shows the same error and i'm confused with the composer. How i can create composer?
I checked that link but i can't follow the steps. Can you explain it briefly?

Thanks.

**Comment by mkalkbrenner** [comment]
First you need to install composer:
http://getcomposer.org/
http://getcomposer.org/doc/00-intro.md

Then switch into the HVClientLibPHP folder and run
php composer.phar install
as described at
https://packagist.org/

**Comment by aneeshasokan13** [comment]
I got this error when trying to install

PEAR repository from http://pear.php.net could not be loaded. The PEAR channel at http://pear.php.net/rest/ is broken. (Invalid XML at file `/c/Web+Services/packagesinfo.xml`)
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for biologis/hv-raw-connector dev-master -> satisfiable by biologis/hv-raw-connector[dev-master].
    - biologis/hv-raw-connector dev-master requires pear-pear.php.net/net_url2 >=2.0.0.0 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by mkalkbrenner** [comment]
I tested it again. I runs smoothly.
Try this:

git clone https://github.com/mkalkbrenner/HVClientLibPHP.git
cd HVClientLibPHP
wget http://getcomposer.org/composer.phar
php composer.phar install

**Comment by aneeshasokan13** [comment]
Thanks, it working now.
But when i run index.php and login in healthvault, it shows like this
We're sorry. HelloWorld-SDK is not supported in your location.

I'm checking this from India? Can i use this from my location?

**Comment by mkalkbrenner** [comment]
AFAIK Microsoft's HelloWorld App is not deployed to all instances. Try to create your HV Account on the US instance. Additionally you can use the third and fourth parameter of the HVClient::connect() method to modify language and country.

**Comment by aneeshasokan13** [comment]
Ok. Its working now. I changed the instance to UK.
Using this library can i upload CCD to healthvault?
Thanks.
